[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pykomodo"
version = "0.0.1"
dependencies = ["pathspec"]

[project.scripts]
komodo = "src.command_line:main"

[tool.setuptools]
packages = ["src"]
zip-safe = false
